version: "3.8"
services: 
  mongo-server:
    container_name: mongo-server
    image: mongo
    restart: always
    ports:
      - 27017:27017
  vue_frontend:
    container_name: vue_frontend
    build: 
      context: ./vue_frontend
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    volumes:
      - ./vue_frontend:/vue_frontend
      - /vue_frontend/node_modules
  node_backend:
    container_name: node_backend
    build: 
      context: ./node_backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo-server
    environment: 
      - MONGO_DB_URI=mongodb://mongo-server/secrets
    ports: 
      - 3000:3000
    volumes:
      - ./node_backend:/node_backend
      - /node_backend/node_modules
